python train.py \
--dataset /home/mveronesi/ml4iot/msc-data \
--models_folder /home/mveronesi/ml4iot/hw2/model/models \
--tflite_models_folder /home/mveronesi/ml4iot/hw2/model/tflite \
--results_folder /home/mveronesi/ml4iot/hw2/model/results \
--frame_length_in_s 0.032 \
--frame_step_in_s 0.016 \
--num_mel_bins 40 \
--lower_frequency 250 \
--upper_frequency 2000 \
--num_coefficients 11 \
--epochs 1
